<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:20:37 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Пълна версия:';
$l['archive_replies'] = 'Отговори';
$l['archive_reply'] = 'Отговор';
$l['archive_pages'] = 'Страници:';
$l['archive_note'] = 'В момента виждате орязана версия на нашия форум. <a href="{1}">Вижте пълната версия</a> с подходящо форматиране.';
$l['archive_reference_urls'] = 'URL за референция';
$l['archive_nopermission'] = 'Съжаляваме! Вие нямате достъп до този ресурс.';
$l['error_nothreads'] = 'В момента няма теми в този форум.';
$l['error_unapproved_thread'] = 'Тази тема не е одобрена. Моля, <a href="{1}">вижте пълната версия</a>, за да видите съдържанието на темата.';
$l['archive_not_found'] = 'Исканата страница не е намерена на този сървър.';
$l['error_mustlogin'] = 'Този форум изисква всички потребители да се вписват.';
$l['error_nopermission'] = 'Вие нямате разрешение да разглеждате теми в този форум.';
