<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra, AndroidBG.com & EasyThe
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1811
// Last edited in MyBB Editor by : admin
// Last edited date : Mon, 26 Jun 2017 04:44:20 +0000
// --------------------------------------------------------------------------------

$l['avatar_gallery'] = 'Галерия с аватари';
$l['avatargallery_info_name'] = 'Галерия с аватари';
$l['avatargallery_info_desc'] = 'Добавя галерия с аватари към вашия форум.';
$l['error_noavatar'] = 'Не сте избрали аватар. Моля, върнете се и го направете сега. Ако не искате аватар, изберете опцията "Без аватар".';
$l['default_gallery'] = 'Галерия по подразбиране';
$l['avatars_in_gallery'] = 'Аватари в {1}';
$l['local_galleries'] = 'Локални галерии с аватари';
$l['gallery'] = 'Галерия:';
$l['change_avatar'] = 'Промяна на аватара';
