<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:37:15 +0000
// --------------------------------------------------------------------------------

$l['avatarep_user_profile'] = 'Профил';
$l['avatarep_user_messages'] = 'Съобщения';
$l['avatarep_user_sendpm'] = 'Изпрати ЛС';
$l['avatarep_user_sendemail'] = 'Изпрати имейл';
$l['avatarep_user_threads'] = 'Преглед на теми';
$l['avatarep_user_error'] = ' Грешка';
$l['avatarep_user_error_text'] = 'Трябва да влезете, за да видите това съдържание';
$l['avatarep_user_alt'] = 'Аватарът на {1}';
$l['avatarep_user_no_avatar'] = 'Без аватар';
$l['avatarep_retrieving'] = 'Извличане на данни
';
$l['avatarep_loading'] = 'Зареждане...';
$l['avatarep_user_alt_forums'] = 'Последна публикация: {1}';
$l['avatarep_user_alt_thread_first'] = 'Първа публикация от: {1}';
$l['avatarep_user_alt_thread_last'] = 'Последна публиакция от: {1}';
$l['avatarep_user_alt_thread_contributor'] = 'Автор на темата: {1}';
