<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:30:58 +0000
// --------------------------------------------------------------------------------

$l['nav_calendar'] = 'Календар';
$l['nav_viewevent'] = 'Вижте събитие';
$l['nav_dayview'] = 'Изглед по дни';
$l['nav_addevent'] = 'Добави събитие';
$l['nav_editevent'] = 'Редактирай събитие';
$l['nav_move_event'] = 'Премести Събитие';
$l['calendar_disabled'] = 'Не можете да използвате функциите на календара, защото са деактивирани от Администратор';
$l['alt_month_1'] = 'Януари';
$l['alt_month_2'] = 'Февруари';
$l['alt_month_3'] = 'Март';
$l['alt_month_4'] = 'Април';
$l['alt_month_5'] = 'Май';
$l['alt_month_6'] = 'Юни';
$l['alt_month_7'] = 'Юли';
$l['alt_month_8'] = 'Август';
$l['alt_month_9'] = 'Септември';
$l['alt_month_10'] = 'Октомври';
$l['alt_month_11'] = 'Ноември';
$l['alt_month_12'] = 'Декември';
$l['add_private_event'] = 'Добавете лично събитие';
$l['add_public_event'] = 'Добавете публично събитие';
$l['calendar'] = 'Календар';
$l['jump_month'] = 'Отидете на месец:';
$l['birthdays_on_day'] = 'Рождени дни на {1}';
$l['birthdayhidden'] = 'Скрит';
$l['event'] = 'събитие';
$l['events'] = 'събития';
$l['add_event'] = 'Добави събитие';
$l['event_date'] = 'Дата на събитие:';
$l['event_recurring_start_date'] = 'Начална дата:';
$l['event_recurring_end_date'] = 'Крайна дата:';
$l['event_recurring_repeat_days'] = 'Събитието се повтаря на:';
$l['event_name'] = 'Име на събитие:';
$l['event_details'] = 'Детайли за събитие:';
$l['event_options'] = 'Опции:';
$l['private_option'] = '<b>Лично</b> Само вие ще може да виждате това събитие. (Само за регистрирани потребители).';
$l['delete_option'] = '<b>Итрий:</b> Изтрий това събитие.';
$l['post_event'] = 'Публикувай събитие';
$l['day_view'] = 'Изглед по дни';
$l['birthday'] = 'Рожден ден';
$l['birthdays'] = 'Рождени дни';
$l['event_author'] = 'Автор на събитие:';
$l['edit_event'] = 'Редактирай събитие';
$l['view_event'] = 'Виж събитие';
$l['no_events'] = 'Този ден няма никакви свързани събития.<p><a href="calendar.php?action=addevent&amp;calendar={1}&amp;day={2}&amp;month={3}&amp;year={4}">Публикувай събитие</a>.</p>';
$l['years_old'] = '{1} Годишен/а';
$l['alt_edit'] = 'Редактирай това събитие';
$l['alt_delete'] = 'Изтрий това събитие';
$l['moderator_options'] = 'Опции за модератор';
$l['approve_event'] = 'Одобри събитие';
$l['unapprove_event'] = 'Неодобри събитие';
$l['move_event'] = 'Премести Събитие';
$l['repeats_every_day'] = 'Повтаря се всеки ден';
$l['repeats_every_x_days'] = 'Повтаря се всеки {1} дни';
$l['repeats_on_weekdays'] = 'Повтаря се от Понеделник до Петък';
$l['every_week_on_days'] = 'Повтаря се всяка седмица на {1}';
$l['every_week'] = 'Повтаря се всяка седмица';
$l['every_x_weeks_on_days'] = 'Повтаря се на {1} седмици на<br />{2}';
$l['every_x_weeks'] = 'Повтаря се на всеки {1} седмици';
$l['every_month_on_day'] = 'Повтаря се на ден {1}<br />от всеки месец';
$l['every_x_months_on_day'] = 'Повтаря се на ден {1}<br />от всеки {2} месеца';
$l['every_month_on_weekday'] = 'Повтаря се на {1} {2}<br />от всеки месец';
$l['every_x_months_on_weekday'] = 'Повтаря се на {1} {2}<br />от всеки {3} месеца';
$l['weekday_occurance_1'] = 'първи';
$l['weekday_occurance_2'] = 'втори';
$l['weekday_occurance_3'] = 'трети';
$l['weekday_occurance_4'] = 'четвърти';
$l['weekday_occurance_last'] = 'последен';
$l['every_year_on_day'] = 'Повтаря се всяка година на {1} {2}';
$l['every_x_years_on_day'] = 'Повтаря се всяка {3} година на {1} {2}';
$l['every_year_on_weekday'] = 'Повтаря се на {1} {2} в {3} от всяка година';
$l['every_x_year_on_weekday'] = 'Повтаря се на {1} {2} в {3} всяка {4} година';
$l['delete_event'] = 'Изтрий събитие';
$l['delete_q'] = 'Изтриване?';
$l['delete_1'] = 'За да изтриете това събитие маркирайте кутийката в ляво и натиснете бутона в дясно.';
$l['delete_2'] = '<b>Бележка:</b> Този процес не може да се върне';
$l['delete_now'] = 'Изтрий сега';
$l['jump_to_calendar'] = 'Преминете в календара:';
$l['select_calendar'] = 'Календар:';
$l['type_single'] = 'Събития в един ден';
$l['type_ranged'] = 'Продължително или повтарящо се събитие';
$l['enter_time'] = 'Време:';
$l['start_time'] = 'Начало:';
$l['end_time'] = 'Край:';
$l['timezone'] = 'Часова зона:';
$l['ignore_timezone'] = '<strong>Игнорирайте часовата зона:</strong> Това събитие ще използва часовата зона на вюъра.';
$l['repeats'] = 'Повторения:';
$l['does_not_repeat'] = 'Да не се повтаря';
$l['repeats_daily'] = 'Дневно';
$l['repeats_weekdays'] = 'Всеки ден от седмицата (Пон-Пет)';
$l['repeats_weekly'] = 'Седмично';
$l['repeats_every'] = 'Повтаря се всеки';
$l['day_or_days'] = 'ден/дни';
$l['week_or_weeks_on'] = 'седмица/и на';
$l['repeats_monthly'] = 'Месечно';
$l['repeats_yearly'] = 'Годишно';
$l['repeats_on_day'] = 'Повтаря се на ден';
$l['of_every'] = 'от всеки';
$l['month_or_months'] = 'месец/и';
$l['repeats_on_the'] = 'Повтаря се на';
$l['day_of_every'] = 'ден всеки';
$l['repeats_on'] = 'Повтаря се на';
$l['every'] = 'всеки';
$l['year_or_years'] = 'година/и';
$l['of'] = 'от';
$l['move_to_calendar'] = 'Премести в календар:';
$l['weekly_overview'] = 'Седмичен изглед';
$l['previous_week'] = 'Предходна седмица';
$l['next_week'] = 'Следваща седмица';
$l['first'] = 'Първи';
$l['second'] = 'Втори';
$l['third'] = 'Трети';
$l['fourth'] = 'Четвърти';
$l['last'] = 'Последен';
$l['all_day'] = 'Цял ден';
$l['starts'] = 'Начало: ';
$l['finishes'] = 'Край: ';
$l['error_incorrectday'] = 'Денят който въвеждате не съществува. Моля, върнете се и опитайте отново.';
$l['error_invalidevent'] = 'Избраното събитие или е невалидно или несъществува';
$l['invalid_calendar'] = 'Избрания календар не съществува. Сигурни ли сте, че посещавате правилната страница?';
$l['redirect_eventdeleted'] = 'Събитието беше успешно изтрито.<br />Ще бъдете пренасочени обратно в календара.';
$l['redirect_eventupdated'] = 'Събитието беше успешно редактирано.<br />Ще бъдете пренасочени към него.';
$l['redirect_eventadded'] = 'Събитието беше добавено успешно.<br />Ще бъдете пренасочени към него.';
$l['redirect_eventadded_moderation'] = 'Събитието беше добавено успешно, но изисква одобрение от форумен модератор преди да е видимо.<br />Ще бъдете пренасочени обратно в календара.';
$l['redirect_eventunapproved'] = 'Събитието беше неодобрено успешно.<br />Ще бъдете пренасочени към него.';
$l['redirect_eventapproved'] = 'Събитието беше одобрено успешно.<br />Ще бъдете пренасочени към него.';
$l['redirect_eventmoved'] = 'Събитието беше преместено успешно.<br />Сега ще бъдете препратени до него.';
$l['delete_no_checkbox'] = 'Събитието не бе изтрито, защото не сте отметнали квадратчето "Изтриване".';
