<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 21:24:37 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'Свържете се с нас';
$l['contact_no_message'] = 'Не сте написали съобщение за изпращане.';
$l['contact_no_subject'] = 'Изисква се въвеждане на заглавие.';
$l['contact_no_email'] = 'Трябва да въведете валиден email адрес.';
$l['contact_success_message'] = 'Съобщението Ви беше успешно изпратено до Администратор.';
$l['contact_subject'] = 'Заглавие';
$l['contact_subject_desc'] = 'Опишете накратко темата на съобшението';
$l['contact_message'] = 'Съобщение';
$l['contact_message_desc'] = 'Опишете Вашето притеснение в това поле подробно.';
$l['contact_email'] = 'Email';
$l['contact_email_desc'] = 'Въведете Вашия email, за да можем да се свържем с Вас.';
$l['contact_send'] = 'Изпратено';
$l['image_verification'] = 'Верификация на изображение';
$l['verification_note'] = 'Моля, въведете текста съдържащ се в изображението в полето под него. Този процес е необходим, за да се предотвратят автоматични съобщения.';
$l['verification_subnote'] = '(чувствителен на символи)';
$l['invalid_captcha'] = 'Верификационният код, който въведохте е неправилен. Моля, въведете кода точно както излиза на изображението.';
$l['subject_too_long'] = 'Заглавието е много дълго. Моля, въведете заглавие по-кратко от {1} символа (в момента са {2}).';
$l['message_too_short'] = 'Съобщението е много късо. Моля, въведете съобщение по-дълго от {1} символа (в момента са {2}).';
$l['message_too_long'] = 'Съобщението е твърде дълго. Моля, въведете съобщение по-кратко от {1} символа (в момента са {2}).';
$l['error_stop_forum_spam_spammer'] = 'Съжаляваме, {1} съвпада с известен спамер, поради това вашето съобщение беше блокирано.';
$l['error_stop_forum_spam_fetching'] = 'Съжаляваме, възникна проблем с верифицирането Ви в спамер базата данни. Най-вероятно базата данни е недостъпна в момента. Моля, опитайте по-късно.';
