<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra, AndroidBG.com & EasyThe
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1811
// Last edited in MyBB Editor by : admin
// Last edited date : Mon, 26 Jun 2017 04:53:27 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = 'Не можете да предупредите никого, тъй като сте достигнали ограничението за брой предупреждения, които можете да давате на ден. <br /> <br /> Максималният брой предупреждения, които можете да дадете на ден, е {1}. "';
$l['warnings_error_invalid_user'] = 'Избраният потребител не съществува.';
$l['warnings_error_invalid_post'] = 'Избраната публикация не съществува.';
$l['warnings_error_cannot_warn_self'] = 'Не можете да добавите към собственото си ниво на предупреждение.';
$l['warnings_error_user_reached_max_warning'] = 'Този потребител не може да бъде предупреден, тъй като вече е достигнал максималното ниво на предупреждение.';
$l['warnings_error_no_note'] = 'Не сте въвели никакви административни бележки за това предупреждение.';
$l['warnings_error_invalid_type'] = 'Избрали сте невалиден тип предупреждение.';
$l['warnings_error_cant_custom_warn'] = 'Нямате право да давате персонализирани предупреждения на потребителите.';
$l['warnings_error_no_custom_reason'] = 'Не сте въвели причина за вашето персонализирано предупреждение.';
$l['warnings_error_invalid_custom_points'] = 'Не сте въвели валиден брой точки, които да добавите към нивото на предупреждение на този потребител. Трябва да въведете цифрова стойност, по-голяма от 0, но не по-голяма от {1}.';
$l['warnings_error_invalid_expires_period'] = 'Въведохте невалиден тип изтичане.';
