<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra, AndroidBG.com & EasyThe
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1811
// Last edited in MyBB Editor by : admin
// Last edited date : Mon, 26 Jun 2017 04:48:34 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'Въведохте невалидна комбинация от потребителско име и парола. <br /><br />Ако сте забравили паролата си, моля, <a href="member.php?action=lostpw">възстановете от тук</a>.';
$l['logindata_invalidpwordusernameemail'] = 'Въведохте невалидна комбинация от имейл и парола. <br /><br />Ако сте забравили паролата си, моля, <a href="member.php?action=lostpw">възстановете от тук</a>.';
$l['logindata_invalidpwordusernamecombo'] = 'Въведохте невалидна комбинация от потребителско име / парола или имейл / парола. <br /><br />Ако сте забравили паролата си, моля, <a href="member.php?action=lostpw">възстановете от тук</a>.';
$l['logindata_regimageinvalid'] = 'Кодът за потвърждаване от изображението, който сте въвели, е неправилен. Моля, въведете кода точно както е показан в изображението.';
$l['logindata_regimagerequired'] = 'Моля, попълнете кода за потвърждаване от изображението, за да продължите процеса на вход. Моля, въведете кода точно както е показан в изображението.';
