<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:30:26 +0000
// --------------------------------------------------------------------------------

$l['postdata_invalid_user_id'] = 'Потребителското id не съществува. Моля, въведете валидно потребителско id.';
$l['postdata_firstpost_no_subject'] = 'Темата е без заглавие, моля задайте!';
$l['postdata_missing_subject'] = 'Не е зададено заглавие, моля задайте!';
$l['postdata_missing_message'] = 'Не е въведен текст, моля въдете!';
$l['postdata_message_too_long'] = 'Текстът е твърде дълъг. Моля, въведете нов, с по-малко от {1} знака (в момента са {2}).';
$l['postdata_message_too_short'] = 'Текстът е твърде кратък. Моля, въведете нов, с повече от {1} знак.';
$l['postdata_subject_too_long'] = 'Заглавието е твърде дълго. Моля, въведете ново, с по-малко от 85 знака (в момента са {1}).';
$l['postdata_post_flooding'] = 'Изминало е твърде малко време от последната Ви публикация. Моля, изчакайте още {1} секунди.';
$l['postdata_post_flooding_one_second'] = 'Изминало е твърде малко време от последната Ви публикация. Моля, изчакайте още 1 секунда.';
$l['postdata_too_many_images'] = 'Публикацията съдържа {1} снимки, докато само {2} снимки на публикация са разрешени. Моля, намалете броя на снимките във Вашата публикация.';
$l['thread_closed'] = 'Затворена тема';
$l['thread_opened'] = 'Отворена тема';
$l['thread_stuck'] = 'Залепена тема';
$l['thread_unstuck'] = 'Отлепена тема';
$l['postdata_banned_username'] = 'Въведеното потребителско име може да не е регистрирано. Моля, въведете друго потребителско име.';
$l['postdata_bad_characters_username'] = 'Въведеното потребителско име съдържа непозволени символи. Моля, въведете друго потребителско име.';
$l['postdata_invalid_username_length'] = 'Въведеното потребителско име е с невалидна дължина. Моля, въведете потребителско име между {1} и {2} символа.';
$l['postdata_too_many_videos'] = 'Въведеното съобщение съдържа {1} видеота, докато само {2} водео/та на съобщение е/са позволено/и. Моля, намалете броя видеота във вашето съобщение, за да отговаря на изискванията.';
$l['postdata_invalid_prefix'] = 'Избрания префикс е невалиден. Моля, изберете валиден префикс.';
$l['postdata_require_prefix'] = 'Форумът изисква въвеждане на префикс на темата. Моля, изберете валиден префикс.';
$l['postdata_username_exists'] = 'Въведеното от вас потребителско име вече съществува. Моля, въведете друго потребителско име.';
