<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 21:12:46 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Нова тема';
$l['moderated_by'] = 'Модератори:';
$l['nothreads'] = 'Съжаляваме, но в момента няма теми в този форум за зададения период от време от опциите.';
$l['search_forum'] = 'Търси във форума:';
$l['thread'] = 'Тема';
$l['author'] = 'Автор';
$l['replies'] = 'Отговори';
$l['views'] = 'Прегледи';
$l['lastpost'] = 'Последен отговор';
$l['rating'] = 'Оценка';
$l['markforum_read'] = 'Маркирай форума като прочетен';
$l['subscribe_forum'] = 'Абониране за форума';
$l['unsubscribe_forum'] = 'Прекратяване на абонамента';
$l['clear_stored_password'] = 'Изчистете съхранените форумни пароли';
$l['sort_by_subject'] = 'Сорт. по: заглавие';
$l['sort_by_lastpost'] = 'Сорт. по: последен отговор';
$l['sort_by_starter'] = 'Сорт. по: автор';
$l['sort_by_started'] = 'Сорт. по: дата на създаване';
$l['sort_by_rating'] = 'Сорт. по: оценка';
$l['sort_by_replies'] = 'Сорт. по: отговори';
$l['sort_by_views'] = 'Сорт. по: прегледи';
$l['sort_order_asc'] = 'Ред: възходящ';
$l['sort_order_desc'] = 'Ред: низходящ';
$l['datelimit_1day'] = 'От: днес';
$l['datelimit_5days'] = 'От: преди 5 дни';
$l['datelimit_10days'] = 'От: преди 10 дни';
$l['datelimit_20days'] = 'От: преди 20 дни';
$l['datelimit_50days'] = 'От: преди 50 дни';
$l['datelimit_75days'] = 'От: преди 75 дни';
$l['datelimit_100days'] = 'От: преди 100 дни';
$l['datelimit_lastyear'] = 'От: миналата година';
$l['datelimit_beginning'] = 'От: началото';
$l['new_thread'] = 'С нови публикации';
$l['new_hot_thread'] = 'Активна тема (Нова)';
$l['posts_by_you'] = 'С ваша публикация';
$l['no_new_thread'] = 'Без нови публикации';
$l['hot_thread'] = 'Активна тема (Стара)';
$l['locked_thread'] = 'Заключена тема';
$l['goto_first_unread'] = 'Отвори първата непрочетена публикация';
$l['pages'] = 'Страници:';
$l['pages_last'] = 'последна';
$l['users_browsing_forum'] = 'Потребители разглеждащи форума:';
$l['users_browsing_forum_guests'] = '{1} гост(и)';
$l['users_browsing_forum_invis'] = '{1} потребител(и) в режим "инкогнито"';
$l['delayed_moderation'] = 'Отложено модериране';
$l['inline_thread_moderation'] = 'Бърза модерация на тема:';
$l['close_threads'] = 'Заключи темите';
$l['open_threads'] = 'Отключи темите';
$l['stick_threads'] = 'Направи темите важни';
$l['unstick_threads'] = 'Направи темите нормални';
$l['delete_threads'] = 'Изтрий темите за винаги';
$l['move_threads'] = 'Премести темите';
$l['approve_threads'] = 'Одобри темите';
$l['unapprove_threads'] = 'Отхвърли темите';
$l['inline_go'] = 'Приложи';
$l['clear'] = 'Изчисти';
$l['sub_forums_in'] = 'Форуми в "{1}"';
$l['forum_rules'] = '{1} - Правила';
$l['subforums'] = '<strong>Подфоруми:</strong>';
$l['asc'] = 'възх.';
$l['desc'] = 'низх.';
$l['forum_announcements'] = 'Форумни обявления';
$l['sticky_threads'] = 'Важни теми';
$l['normal_threads'] = 'Теми';
$l['icon_dot'] = 'С ваша публикация. ';
$l['icon_new'] = 'Нови публикации.';
$l['icon_hot'] = ' Активна тема.';
$l['icon_lock'] = ' Заключена тема.';
$l['attachment_count'] = 'Темата съдържа един прикачен файл.';
$l['attachment_count_multiple'] = 'Темата съдържа {1} прикачени файла.';
$l['rss_discovery_forum'] = 'Последните теми в {1}';
$l['forum_unapproved_posts_count'] = 'В момента има {1} отхвърлени публикации в този форум.';
$l['forum_unapproved_post_count'] = 'В момента има 1 отхвърлена публикация в този форум.';
$l['forum_unapproved_threads_count'] = 'В момента има {1} отхвърлени теми в този форум.';
$l['forum_unapproved_thread_count'] = 'В момента има 1 отхвърлена тема в този форум.';
$l['thread_unapproved_posts_count'] = 'В момента има {1} отхвърлени публикации в тази тема.';
$l['thread_unapproved_post_count'] = 'В момента има 1 отхвърлена публикация в тази тема.';
$l['page_selected'] = 'Всичките <strong>{1}</strong> теми от страницата са избрани.';
$l['all_selected'] = 'Всичките <strong>{1}</strong> във форума са избрани.';
$l['select_all'] = 'Избиране на всички <strong>{1}</strong> теми във форума.';
$l['clear_selection'] = 'Изчистване на избраните.';
$l['error_containsnoforums'] = 'За съжаление форумът, който преглеждате не съдържа подфоруми.';
$l['prefix'] = 'Префикс:';
$l['prefix_all'] = 'Префикс: Всеки/Без префикс';
$l['prefix_any'] = 'Префикс: Всеки префикс';
$l['prefix_none'] = 'Префикс: Без префикс';
$l['soft_delete_threads'] = 'Бързо изтриване на теми';
$l['restore_threads'] = 'Възстанови теми';
$l['icon_no_new'] = 'Няма нови публикации.';
$l['inline_edit_description'] = '(Натиснете и задръжте за редакция)';
$l['nopermission'] = 'Съжаляваме, но нямате право да преглеждате теми в този раздел.';
$l['deleted_thread'] = 'Изтрита тема';
