<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra, AndroidBG.com & EasyThe
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1811
// Last edited in MyBB Editor by : admin
// Last edited date : Mon, 26 Jun 2017 05:12:10 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Здравей Свят!';
$l['hello_add'] = 'Добави';
$l['hello_add_message'] = 'Добави съобщение';
$l['hello_empty'] = 'Не са намерени съобщения.';
$l['hello_message_empty'] = 'Съобщението не може да бъде празно.';
$l['hello_done'] = 'Съобщението е добавено успешно.';
