<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Fri, 02 Jan 2015 22:46:07 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Списък с членове';
$l['memberlist_disabled'] = 'Функциалността на списъка с членове е забранена от Администратор';
$l['member_list'] = 'Списък с членове';
$l['avatar'] = 'Аватар';
$l['username'] = 'Потребителско име';
$l['joined'] = 'Присъединил се';
$l['lastvisit'] = 'Последно посещение';
$l['posts'] = 'Брой публикации';
$l['referrals'] = 'Реферали';
$l['search_members'] = 'Търсене в Списък с членове';
$l['website'] = 'Уеб адрес';
$l['sort_by'] = 'Сортирай по';
$l['contains'] = 'Съдържа:';
$l['sort_by_username'] = 'Сорт. по: Потребителско име';
$l['sort_by_regdate'] = 'Сорт. по: Дата на регистрация';
$l['sort_by_lastvisit'] = 'Сорт. по: Последно посещение';
$l['sort_by_posts'] = 'Сорт. по: Брой публикации';
$l['sort_by_referrals'] = 'Сорт. по: Референтни членове';
$l['order_asc'] = 'възходящ ред';
$l['order_desc'] = 'низходящ ред';
$l['forumteam'] = 'Покажи Екипа на форума';
$l['advanced_search'] = 'Подробно търсене';
$l['search_member_list'] = 'Търси в Списък с членове';
$l['search_criteria'] = 'Критерий за търсене';
$l['begins_with'] = 'започва с';
$l['username_contains'] = 'съдържа';
$l['search_website'] = 'URL на Уеб адрес';
$l['search_aim'] = 'AIM Screen Name';
$l['search_msn'] = 'Windows Live Messenger Address';
$l['search_yahoo'] = 'Yahoo! Messenger Screen Name';
$l['search_icq'] = 'ICQ Number';
$l['search_options'] = 'Опции за търсене';
$l['per_page'] = 'Резултати на страница';
$l['search'] = 'Търси';
$l['error_no_members'] = '<p>Не са намерени членове по въведеният критерий за търсене.</p><p>Моля, въведете други критерий и опитайте отново.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
$l['threads'] = 'Брой теми';
$l['sort_by_threads'] = 'Сорт. по: Брой теми';
$l['asc'] = 'възх.';
$l['desc'] = 'низх.';
$l['nav_memberlist_search'] = 'Търси';
$l['search_skype'] = 'Skype адрес';
$l['search_google'] = 'Google+ (Hangouts) адрес';
$l['search_user'] = 'Търси потребител';
