<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:09:01 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Помощни документи';
$l['nav_smilies'] = 'Списък на емотикони';
$l['nav_syndication'] = 'Последна синдикирана тема (RSS)';
$l['aol_im'] = 'AOL IM';
$l['msn'] = 'MSN Messenger';
$l['yahoo_im'] = 'Yahoo IM';
$l['msn_messenger_center'] = 'MSN Messenger Center';
$l['msn_address_is'] = 'MSN Address на {1} е:';
$l['yahoo_center'] = 'Yahoo! Center';
$l['send_y_message'] = 'Изпрати на {1} Yahoo! съобщение.';
$l['view_y_profile'] = 'Вижте Yahoo! Профила на {1}.';
$l['aim_center'] = 'AOL IM Center';
$l['download_aim'] = 'Свали AIM';
$l['aim_remote'] = 'AIM Remote';
$l['send_me_instant'] = 'Изпрати ми незабавно съобщение';
$l['add_me_buddy_list'] = 'Добави ме в Списък с приятели';
$l['add_remote_to_page'] = 'Добави дистанционно във Вашата страница';
$l['download_aol_im'] = 'Свали AOL Instant Messenger';
$l['buddy_list'] = 'Списък с приятели';
$l['online'] = 'Онлайн';
$l['offline'] = 'Офлайн';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'Изпрати лично съобщение';
$l['last_active'] = '<strong>Последно активен:</strong> {1}';
$l['close'] = 'Затвори';
$l['no_buddies'] = '<em>Вашият Списък с приятели в момента е празен. Използвайте потребителския панел или посетете потребителски профил, за да добавите потребители във Вашия списък с приятели.</em>';
$l['help_docs'] = 'Помощни dокументи';
$l['smilies_listing'] = 'Списък с усмивки';
$l['name'] = 'Име';
$l['abbreviation'] = 'Абревиатура';
$l['click_to_add'] = 'Кликнете на усмивка, за да я вмъкнете към Вашето съобщение';
$l['close_window'] = 'затвори прозорец';
$l['who_posted'] = 'Кой публикува?';
$l['total_posts'] = 'Общо публикации:';
$l['user'] = 'Потребител';
$l['num_posts'] = '# Публикация';
$l['forum_rules'] = '{1} - Правила';
$l['error_invalid_limit'] = 'Въведеният лимит на елементи е невалиден. Моля, посочете валиден лимит.';
$l['syndication'] = 'Последна синдикирана тема';
$l['syndication_generated_url'] = 'Вие генерирахте синдикиран URL адрес:';
$l['syndication_note'] = 'Отдолу може да генерирате линкове за специфични RSS feeds. Могат да се генерират линкове за всички форуми, за един форум или за специфичен брой форуми. След това ще Ви се даде линк, който можете да копирате във Вашия RSS четец, като <a href="http://www.sharpreader.net/">SharpReader</a>. <i><a href="http://www.xml.com/pub/a/2002/12/18/dive-into-xml.html">Какво е RSS?</a></i>';
$l['syndication_forum'] = 'Форум за синдикиране:';
$l['syndication_forum_desc'] = 'Моля, изберете форум от дясно. Използвайте клавиш CTRL, за да изберете няколко форума.';
$l['syndication_version'] = 'Feed Версия:';
$l['syndication_version_desc'] = 'Моля, изберете версия на feed-овете, които искате да генерирате.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00 (По подразбиране)';
$l['syndication_generate'] = 'Генерирайте синдикиран URL';
$l['syndication_limit'] = 'Лимит:';
$l['syndication_limit_desc'] = 'Количеството теми за сваляне едновременно. Не се препоръчва да е над 50.';
$l['syndication_threads_time'] = 'теми наведнъж';
$l['syndicate_all_forums'] = 'Синдикирай целия форум';
$l['redirect_markforumread'] = 'Избраният форум беше маркиран като прочетен.';
$l['redirect_markforumsread'] = 'Всички форуми бяха маркирани като прочетени.';
$l['redirect_forumpasscleared'] = 'Запаметената парола за този форум беше изчистена.';
$l['redirect_cookiescleared'] = 'Всички бисквитки бяха почистени.';
$l['error_invalidimtype'] = 'Потребителят няма посочен такъв instant messenger акаунт в неговия профил.';
$l['error_invalidhelpdoc'] = 'Посоченият помощен документ не съществува.';
$l['error_invalidkey'] = 'Не може да бъдете верифицирани, за да изчистите бисквитките. Това може да се дължи на злонамерен Javascript, който се опитва да изчисти бисквитките автоматично. Ако имате намерение да изчистите бисквитките, моля, вижте помощен документ "Използване на Cookies в MyBB".';
$l['dst_settings_updated'] = 'Настройката за лятното часово време беше автоматично коригирана.<br /><br />Ще бъдете пренасочени към индекса на форума.';
$l['skype'] = 'Skype';
$l['skype_center'] = 'Skype Center';
$l['skype_status'] = 'Skype Status';
$l['chat_on_skype'] = 'Пишете с {1} по Skype';
$l['call_on_skype'] = 'Обадете се на {1} по Skype';
$l['online_none'] = '<em>Нямате приятели онлайн</em>';
$l['offline_none'] = '<em>Нямате приятели офлайн</em>';
$l['search_help_documents'] = 'Търсете помощни документи';
$l['search_by_name'] = 'Търсене по Име';
$l['search_by_document'] = 'Търсене по Документ';
$l['enter_keywords'] = 'Въведете ключови думи';
$l['search'] = 'Търси';
$l['redirect_searchresults'] = 'Благодарим, Вашето търсене беше изпратено и сега ще бъдете препратени към списъка с резултатите.';
$l['search_results'] = 'Резултати';
$l['help_doc_results'] = 'Резултати от Помощни документи';
$l['document'] = 'Документи';
$l['error_nosearchresults'] = 'Съжаляваме, не бяха намерени резултати от въведената от Вас информация. Моля, променете критериите за търсене и опитайте отново.';
$l['no_help_results'] = 'Съжаляваме, не бяха намерени резултати от въведената от Вас информация.';
$l['error_helpsearchdisabled'] = 'Възможноста за търсене на Помощни документи е деактивирана от Администратор ';
$l['no_smilies'] = 'Понастоящем няма емотикони.';
$l['error_invalidforum'] = 'Невалиден форум';
$l['error_invalidsearch'] = 'Бе определено невалидно търсене. Моля, върнете се и опитайте отново.';
$l['error_no_search_support'] = 'Базата данни не поддържа търсене.';
$l['error_searchflooding'] = 'За съжаление можете да извършите само едно търсене на всеки {1} секунди. Моля, изчакайте още {2} секунди, преди да опитате отново да търсите.';
$l['error_searchflooding_1'] = 'За съжаление можете да извършите само едно търсене на всеки {1} секунди. Моля, изчакайте още 1 секунда, преди да опитате отново да търсите.';
