<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:27:12 +0000
// --------------------------------------------------------------------------------

$l['myadvertisements_pm_subject'] = 'Изтекли реклами';
$l['myadvertisements_pm_message'] = 'Advertisement whose name is {1} has expired. Ad ID: {2}';
$l['myadvertisements_task_ran'] = 'My Advertisements задачата е изпълнена.';
$l['myadvertisements_at'] = 'в';
$l['myadvertisements_stats_email'] = 'Кликвания: {1}; Прегледи: {2}';
