<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 22:13:36 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Публикуване на нов отговор';
$l['post_reply_to'] = 'Публикуване на отговор в {1}';
$l['post_new_reply'] = 'Публикуване на отговор';
$l['reply_to'] = 'Отговор в тема: {1}';
$l['post_subject'] = 'Тема на публикацията:';
$l['your_message'] = 'Текст:';
$l['post_options'] = 'Опции:';
$l['options_sig'] = '<strong>Подписване:</strong> вмъкване на подписа Ви в публикацията (само за регистрирани потребители)';
$l['options_emailnotify'] = '<strong>Известяване с e-mail:</strong> получаване на e-mail при публкуване на отговор (само за регистрирани потребители)';
$l['options_disablesmilies'] = '<strong>Деактивиране на емотиконите:</strong> без емотикони в темата';
$l['post_reply'] = 'Публикуване';
$l['preview_post'] = 'Преглед';
$l['mod_options'] = 'Модераторски опции:';
$l['close_thread'] = '<strong>Заключи темата</strong>: публикуването на нови отговори няма да бъде възможно';
$l['stick_thread'] = '<strong>Направи темата важна:</strong> темата ще стой в началото на списъка с теми';
$l['forum_rules'] = '{1} - Правила';
$l['thread_review'] = 'Преглед на тема (първо новите)';
$l['thread_review_more'] = 'Тази тема има повече от {1} отговора. <a href="{2}">Прочети цялата тема.</a>';
$l['posted_by'] = 'Пъбликуван от';
$l['draft_saved'] = 'Новата публикация беше запаметена като чернова.<br />Ще бъдете пренасочен към вашия списък с чернови.';
$l['image_verification'] = 'Верификация на изображение';
$l['verification_note'] = 'Моля, въведете текста съдържащ се в изображението в полето под него. Този процес се използва за предотвратяване на автоматизирани публикации.';
$l['verification_subnote'] = '(чувствителни символи)';
$l['invalid_captcha'] = 'Въведения код за потвърждение не е правилен. Моля, въведете кода точно както се вижда на изображението.';
$l['error_post_already_submitted'] = 'Вече сте публикували отговора в темата.';
$l['multiquote_external_one'] = 'Маркирали сте една публикация от друга тема.';
$l['multiquote_external'] = 'Маркирали сте {1} публикации от други теми.';
$l['multiquote_external_one_deselect'] = 'размаркирай публикацията';
$l['multiquote_external_deselect'] = 'размаркирай публикациите';
$l['multiquote_external_one_quote'] = 'Цитирай и тази публикация';
$l['multiquote_external_quote'] = 'Цитирай и тези публикации';
$l['redirect_newreply'] = 'Благодарим ви! Отговорът е публикуван.';
$l['redirect_newreply_moderation'] = 'Администраторът изисква всеки нов отговор да бъде одобрен преди публикуването му. Ще бъде заредена темата.';
$l['redirect_newreply_post'] = '<br />Ще бъде заредена публикацията.';
$l['redirect_newreplyerror'] = 'За съжаление отговорът Ви е отхвърлен, поради липса на съдържание. <br />Ще бъде заредена темата.';
$l['redirect_threadclosed'] = 'Не можете да публикувате отговор, защото темата е заключена от модератор.';
$l['error_post_noperms'] = 'Нямате правомощия да редактирате черновата.';
$l['error_stop_forum_spam_spammer'] = 'Съжаляваме, вашият {1} съвпада с данните на познат спамер. Ако смятате, че това е грешка, моля, свържете се с Администратор.';
$l['error_stop_forum_spam_fetching'] = 'Съжаляваме, нещо се обърка при верификацията на Вашия отговор в спамер базата данни. Най-вероятно базата данни не е достъпна в момента. Моля, опитайте по-късно.';
$l['error_suspendedposting'] = 'Правата Ви за публикуване в момента са спрени {1}.<br /><br />

Дата на забрана: {2}';
$l['error_suspendedposting_temporal'] = 'до {1}';
$l['error_suspendedposting_permanent'] = 'постоянно';
