<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 21:26:33 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = 'Нова тема';
$l['newthread_in'] = 'Нова тема в {1}';
$l['post_new_thread'] = 'Публикуване на нова тема';
$l['thread_subject'] = 'Заглавие на темата';
$l['your_message'] = 'Текст:';
$l['post_options'] = 'Опции:';
$l['options_sig'] = '<b>Подписване:</b> вмъкване на подпис в публикацията (само за регистрирани потребители)';
$l['options_emailnotify'] = '<b>Известяване с e-mail:</b> получаване на e-mail при публкуване на отговор (само за регистрирани потребители)';
$l['options_disablesmilies'] = '<b>Деактивиране на емотиконите:</b> без емотикони в темата';
$l['post_thread'] = 'Публикуване';
$l['preview_post'] = 'Преглед';
$l['poll'] = 'Анкета:';
$l['poll_desc'] = 'Можете да добавите анкета към темата.';
$l['poll_check'] = 'Публикуване на анкета';
$l['num_options'] = 'Брой опции за избор:';
$l['max_options'] = '(Максимално: {1})';
$l['mod_options'] = 'Модераторски опции:';
$l['close_thread'] = '<b>Заключи темата</b>: публикуването на нови отговори няма да бъде възможно';
$l['stick_thread'] = '<b>Закачи темата като важна:</b> темата ще стои в началото на списъка с теми';
$l['draft_saved'] = 'Новата тема е записана успешно като чернова.<br />Ще бъде зареден списъка с чернови.';
$l['image_verification'] = 'Верификация на изображение';
$l['verification_note'] = 'Моля, въведете текста съдържащ се в изображението в полето под него. Този процес се използва, за предотвратяване на автоматизирани публикации.';
$l['verification_subnote'] = '(чувствителни символи)';
$l['invalid_captcha'] = 'Въведения код за потвърждение не е правилен. Моля, въведете кода точно, както се вижда на изображението.';
$l['error_post_already_submitted'] = 'Вече сте публикували темата във форума.';
$l['no_prefix'] = 'Без представка';
$l['forum_rules'] = '{1} - Правила';
$l['multiquote_external_one'] = 'Маркирали сте една публикация от друга тема.';
$l['multiquote_external'] = 'Маркирали сте {1} публикации от други теми.';
$l['multiquote_external_one_deselect'] = 'размаркирай публикацията';
$l['multiquote_external_deselect'] = 'размаркирай публикациите';
$l['multiquote_external_one_quote'] = 'Цитирай и тази публикация';
$l['multiquote_external_quote'] = 'Цитирай и тези публикации';
$l['redirect_newthread'] = 'Благодарим ви! Темата е публикувана.';
$l['redirect_newthread_poll'] = '<br />Ще бъде заредена страницата с настройки за анкетата.';
$l['redirect_newthread_moderation'] = '<br />Администраторът изисква всяка тема да бъде одобрена преди публикуването й. Ще бъдете върнати към списъка с теми.';
$l['redirect_newthread_thread'] = '<br />Зареждане на списъка с теми.';
$l['invalidthread'] = 'Дадената чернова не съществува или нямате права да я преглеждате.';
$l['error_stop_forum_spam_spammer'] = 'Съжаляваме, вашият {1} съвпада с данните на познат спамер. Ако смятате, че това е грешка, моля, свържете се с Администратор.';
$l['error_stop_forum_spam_fetching'] = 'Съжаляваме, нещо се обърка при верификацията на Вашия отговор в спамер базата данни. Най-вероятно базата данни не е достъпна в момента. Моля, опитайте по-късно.';
$l['error_suspendedposting'] = 'Правата Ви за публикуване в момента са спрени {1}.<br /><br />

Дата на забрана: {2}';
$l['error_suspendedposting_temporal'] = 'до {1}';
$l['error_suspendedposting_permanent'] = 'постоянно';
$l['redirect_newthread_unviewable'] = '<br />Вие нямате право да преглеждате теми в този форум. Ще бъдете върнати във форума.';
