<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Fri, 02 Jan 2015 23:15:12 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Кой е онлайн';
$l['nav_onlinetoday'] = 'Кой е бил онлайн днес';
$l['viewing_announcements'] = 'Разглежда <a href="{1}">{2}</a> обявления';
$l['viewing_announcements2'] = 'Разглежда форумни обявления';
$l['viewing_attachment'] = 'Разглежда прикачени файлове';
$l['viewing_attachment2'] = 'Разглежда <a href="attachment.php?aid={1}" target="_blank">прикачени файлове</a> в тема <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'Разглежда <a href="calendar.php">календар</a>';
$l['viewing_event'] = 'Разглежда събитие';
$l['viewing_event2'] = 'Разглежда събитие <a href="{1}">{2}</a>';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Добавя събитие</a>';
$l['editing_event'] = 'Редактира събитие';
$l['editing_post'] = 'Редактира публикация';
$l['viewing_forum'] = 'Разглежда форум';
$l['viewing_forum2'] = 'Разглежда форум <a href="{1}">{2}</a>';
$l['forum_redirect_to'] = 'Е пренасочен към <a href="{1}">{2}</a>';
$l['viewing_index'] = '{1} <a href="index.php">Основен индекс</a>';
$l['activating_account'] = 'Активира акаунт';
$l['viewing_profile'] = 'Разглежда профил';
$l['viewing_profile2'] = 'Разглежда профил на <a href="{1}">{2}</a>';
$l['registering'] = '<a href="member.php?action=register">Регистрира се</a>';
$l['logging_in'] = '<a href="member.php?action=login">Влиза</a>';
$l['logging_in_plain'] = 'Вход';
$l['logging_out'] = 'Изход';
$l['emailing_user'] = 'Пише e-mail до потребител';
$l['rating_user'] = 'Оценява потребител';
$l['viewing_memberlist'] = 'Разглежда <a href="memberlist.php">списък с членове</a>';
$l['viewing_whoposted'] = 'Разглежда кой публикува';
$l['viewing_whoposted2'] = 'Разглежда кой публикува в тема <a href="{1}">{2}</a>';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Прави форуми като прочетени</a>';
$l['viewing_helpdocs'] = 'Разглежда <a href="misc.php?action=help">помощни документи</a>';
$l['viewing_buddylist'] = 'Разглежда <a href="misc.php?action=buddypopup">списък с приятели</a>';
$l['viewing_smilies'] = 'Разглежда <a href="misc.php?action=smilies">списък с емотикони</a>';
$l['viewing_syndication'] = 'Разглежда <a href="misc.php?action=syndication">страницата RSS Syndication</a>';
$l['replying_thread'] = 'Отговаря в тема';
$l['replying_thread2'] = 'Отговаря в тема <a href="{1}">{2}</a>';
$l['posting_thread'] = 'Публикува нова тема';
$l['posting_thread2'] = 'Публикува нова тема в <a href="{1}">{2}</a>';
$l['viewing_wol'] = 'Разглежда <a href="online.php">кой е онлайн</a>';
$l['viewing_woltoday'] = 'Разглежда <a href="online.php?action=today">кой е онлайн Днес</a>';
$l['creating_poll'] = 'Създава нова анкета';
$l['editing_poll'] = 'Редактира анкета';
$l['viewing_pollresults'] = 'Разглежда резултати в анкета';
$l['voting_poll'] = 'Гласува в анкета';
$l['using_modtools'] = 'Използва модераторски инструмент';
$l['sending_pm'] = 'Изпраща лично съобщение';
$l['reading_pm'] = 'Чете лично съобщение';
$l['editing_pmfolders'] = 'Редактира ЛС папка';
$l['using_pmsystem'] = 'Използва ЛС системата';
$l['reporting_post'] = 'Докладва публикация';
$l['searching_forum'] = '<a href="search.php">Търси</a> {1}';
$l['reading_thread'] = 'Чете тема';
$l['reading_thread2'] = 'Чете тема <a href="{1}">{2}</a> {3}';
$l['viewing_team'] = 'Разглежда екипа на Форума';
$l['viewing_stats'] = 'Разглежда статистиката на форума';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Обновява профил</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Обновява опции</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Редактира подпис</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Сменя аватар</a>';
$l['viewing_subscriptions'] = 'Разглежда <a href="usercp.php?action=subscriptions">абонаменти</a>';
$l['viewing_favorites'] = 'Разглежда <a href="usercp.php?action=favorites">любими теми</a>';
$l['editing_pad'] = 'Редактира <a href="usercp.php?action=notepad">личен бележник</a>';
$l['editing_password'] = 'Редактира <a href="usercp.php?action=password">парола</a>';
$l['user_cp'] = 'Разглежда <a href="usercp.php">потребителски панел</a>';
$l['viewing_portal'] = 'Разглежда <a href="portal.php">портала</a>';
$l['viewing_noperms'] = 'Разглежда страницата "Без разрешение"';
$l['unknown_location'] = '<a href="{1}">Неизвестно местоположение</a>';
$l['giving_reputation'] = 'Дава репутация на <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = 'Разглежда <a href="{1}"> репутация на {2}</a>';
$l['member_resendactivation'] = 'Препраща активационен e-mail';
$l['member_lostpw'] = 'Възстановява <a href="member.php?action=lostpw">забравена парола</a>';
$l['sending_thread'] = 'Изпраща тема на приятел';
$l['guest'] = 'Гост';
$l['page'] = 'Страница';
$l['users_online'] = 'Кой е онлайн';
$l['on_username'] = 'Потребителско име';
$l['time'] = 'Време';
$l['location'] = 'Местоположение';
$l['online_today'] = 'Кой е бил онлайн днес';
$l['refresh_page'] = 'Презареди тази страница';
$l['online_online_plural'] = 'потребители';
$l['online_online_singular'] = 'потребител';
$l['online_member_plural'] = 'членове';
$l['online_member_singular'] = 'член';
$l['online_anon_plural'] = 'са';
$l['online_anon_singular'] = 'е';
$l['online_guest_plural'] = 'гости';
$l['online_guest_singular'] = 'гост';
$l['online_count'] = '{1} {2} активира в последните {3} минути ({4} {5}, {6} от които {7} невидим и {8} {9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Host име:';
$l['if_resolvable'] = '(ако е разрешим)';
$l['admin_options'] = 'Администраторски опции:';
$l['search_regip_users'] = 'Търсене на потребителите регистрирали се с това IP';
$l['search_postip_users'] = 'Намери потребители, които са публикували от това IP';
$l['lookup'] = '[търсене]';
$l['member_online_today'] = '<strong>1</strong> член е бил онлайн днес';
$l['members_were_online_today'] = '<strong>{1}</strong> члена са били онлайн днес';
$l['member_online_hidden'] = ' ({1} член е бил инкогнито)';
$l['members_online_hidden'] = ' ({1} членове са били инкогнито)';
$l['rating_thread'] = 'Оценява тема';
$l['viewing_imcenter'] = 'Разглежда IM Center';
$l['managing_favorites'] = 'Управлява любимите теми';
$l['managing_subscriptions'] = 'Управлява абонираните теми';
$l['managing_group'] = 'Управлява потребителска група';
$l['viewing_modcp'] = 'Разглежда модераторски панел';
$l['viewing_modlogs'] = 'Разглежда модераторски лог';
$l['managing_announcements'] = 'Управлява обявленията';
$l['search_for_user'] = 'Търси потребители';
$l['managing_warninglogs'] = 'Управлява предупреждения';
$l['searching_ips'] = 'Търси IP-та';
$l['viewing_reports'] = 'Разглежда доклади';
$l['adding_announcement'] = 'Добавя обявление';
$l['deleting_announcement'] = 'Трие обявление';
$l['editing_announcement'] = 'Редактира обявление';
$l['managing_modqueue'] = 'Управлява модераторски заявки';
$l['editing_user_profiles'] = 'Редактира потребителски профили';
$l['managing_bans'] = 'Управлява банове';
$l['revoking_warning'] = 'Анулира предупреждение';
$l['warning_user'] = 'Предупреждава потребител';
$l['viewing_warning'] = 'Разглежда предупреждение';
$l['managing_warnings'] = 'Управлява предупреждения';
$l['changing_dst'] = 'Променя DST превключвател';
$l['printing_thread'] = 'Принтира тема';
$l['printing_thread2'] = 'Принтира тема <a href="{1}">{2}</a>';
$l['managing_buddyignorelist'] = 'Управлява списък с приятели/списък с игнорирани';
$l['viewing_contact_us'] = 'Разглежда <a href="contact.php">Свържи се с нас</a>';
$l['viewing_reputation_report2'] = 'Разглежда репутация';
