<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:21:48 +0000
// --------------------------------------------------------------------------------

$l['online_note_today'] = '{1} {2} активни в последните {3} часа {{4} {5}, {6} от които {7} невидими и {8} {9}).';
$l['whos_online_today'] = 'Кой е бил онлайн днес';
