<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Sat, 03 Jan 2015 09:39:32 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Портал';
$l['posted_by'] = 'Публикувано от:';
$l['replies'] = 'Отговори';
$l['no_replies'] = 'Без отговори';
$l['latest_threads'] = 'Последни теми';
$l['latest_threads_replies'] = 'Отговори:';
$l['latest_threads_views'] = 'Разглеждания:';
$l['latest_threads_lastpost'] = 'Последна публикация:';
$l['private_messages'] = 'Лични съобщения';
$l['pms_received_new'] = '{1}, имате <b>{2}</b> съобщение(я).';
$l['pms_unread'] = 'Непрочетени съобщения';
$l['pms_total'] = 'Общо съобщения';
$l['search_forums'] = 'Търси форуми';
$l['advanced_search'] = 'Разширено търсене';
$l['forum_stats'] = 'Форумни статистики';
$l['num_members'] = 'Членове:';
$l['latest_member'] = 'Последен член:';
$l['num_threads'] = 'Форумни теми:';
$l['num_posts'] = 'Форумни публикации:';
$l['full_stats'] = 'Пълна статистика';
$l['welcome'] = 'Привет, {1}';
$l['guest'] = 'Гост';
$l['guest_welcome_registration'] = 'Трябва да се <a href="{1}">регистрирате</a> преди да може да публикувате на нашия сайт.';
$l['username'] = 'Потребителско име';
$l['password'] = 'Парола';
$l['login'] = 'Влизане!';
$l['member_welcome_lastvisit'] = 'Последно посещение:';
$l['since_then'] = 'От тогава е имало:';
$l['new_announcements'] = '{1} нови обявления';
$l['new_announcement'] = '1 ново обявление';
$l['new_threads'] = '{1} нови теми';
$l['new_thread'] = '1 нова тема';
$l['new_posts'] = '{1} нови публикации';
$l['new_post'] = '1 нова публикация';
$l['view_new'] = 'Виж нови публикации';
$l['view_todays'] = 'Виж днешни публикации';
$l['online'] = 'Онлайн потребители';
$l['online_user'] = 'В момента има 1 потребител онлайн';
$l['online_users'] = 'В момента има <b>{1}</b> потребители онлайн.';
$l['online_counts'] = '<b>{1}</b> Член/а | <b>{2}</b> Гост/и';
$l['no_one'] = 'no-one';
$l['print_this_item'] = 'Принтирай';
$l['send_to_friend'] = 'Избрати на приятел';
$l['forum'] = 'Форум:';
$l['latest_announcements'] = 'Последни обявления';
$l['portal_disabled'] = 'Не можете да използвате функционалноста на портала, тъй като е деактивиран от Администратор';
