<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Fri, 02 Jan 2015 23:24:49 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Благодарим, темата беше оценена успешно. Ще бъдете пренасочени обратно към темата.';
$l['error_invalidrating'] = 'Избрали сте невалидна оценка за тази тема. Моля, върнете се обратно и опитайте отново.';
$l['error_alreadyratedthread'] = 'Съжаляваме, но вече сте оценил тази тема.';
$l['rating_votes_average'] = '{1} Глас(а) - {2} от 5 средно';
$l['one_star'] = '1 звезда от 5';
$l['two_stars'] = '2 звезди от 5';
$l['three_stars'] = '3 звезди от 5';
$l['four_stars'] = '4 звезди от 5';
$l['five_stars'] = '5 звезди от 5';
$l['rating_added'] = 'Вашата оценка беше добавена!';
$l['error_cannotrateownthread'] = 'Съжаляваме, не можете да оцените собствена тема.';
