<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 22:00:25 +0000
// --------------------------------------------------------------------------------

$l['report_post'] = 'Докладвай публикация';
$l['report_to_mod'] = 'Докладвай тази публикация на модератор';
$l['only_report'] = 'Трябва да докладвате само публикации, които са спам, реклама, обида или неотговарящи на правилата на форума.';
$l['report_reason'] = 'Причината за докладване на тази публикация:';
$l['thank_you'] = 'Благодарим Ви.';
$l['post_reported'] = 'Публикацията беше успешно докладвана. Можете да затворите този прозорец.';
$l['report_error'] = 'Грешка';
$l['no_reason'] = 'Не можете да докладвате публикация без да посочите причина.';
$l['go_back'] = 'Назад';
$l['close_window'] = 'Затвори прозорец';
$l['report_content'] = 'Докладвай съдържание';
$l['report_reason_post'] = 'Докладвай публикация';
$l['report_reason_profile'] = 'Докладвай профил';
$l['report_reason_reputation'] = 'Докладвай репутация';
$l['report_reason_bad'] = 'Неподходящо съдържание';
$l['report_reason_spam'] = 'Спам съдържание';
$l['report_reason_rules'] = 'Нарушава правилата на форума';
$l['report_reason_wrong'] = 'Грешен форум';
$l['report_reason_other'] = 'Друго';
$l['success_report_voted'] = 'Благодарим, че докладвахте това съдържание.<br />Член на екипа ще провери доклада в най-скоро време. ';
$l['error_report_length'] = 'Моля, дайте подробна причина за Вашия доклад.';
$l['error_invalid_report'] = 'Съдържанието не съществува или няма възможност да бъде докладвано.';
$l['error_report_duplicate'] = 'Съдържанието вече е докладвано от друг член.<br />Вие също можете да докладвате това съдържание отдолу.';
$l['report_reason_other_description'] = 'В "Друго" моля, дайте причина за доклада на това съдържание.';
$l['error_invalid_report_reason'] = 'Избраната причина е невалидна.';
$l['error_comment_required'] = 'Нужен е допълнителен коментар за избраната причина.';
