<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 21:49:11 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'Отчет за репутация';
$l['nav_profile'] = 'Профил на {1}';
$l['reputation_disabled'] = 'Не можете да използвате системата за репутация, тъй като е деактивирана от Администратора.';
$l['reputation'] = 'Репутация';
$l['error'] = 'Грешка';
$l['add_no_uid'] = 'Не сте посочили потребтел, на който да дадете репутация.';
$l['add_no_permission'] = 'Нямате права да давате репутация на потребители.';
$l['add_disabled'] = 'Не можете да давате репутация на потребителите в тази потребителска група.';
$l['add_yours'] = 'Не можете да давате репутация на себе си. Егоист!!!';
$l['add_invalidpower'] = 'Избрали сте невалидна оценка от списъка.';
$l['add_maxperday'] = 'Дали сте толкова репутации, колкото е позволено за днес.';
$l['add_maxperuser'] = 'Дали сте толкова репутация на този потребител, колкото е позволено за днес.';
$l['add_maxperthread'] = 'Дали сте толкова репутация на този потребител (в една тема), колкото е позволено за днес.';
$l['add_no_comment'] = 'Въведете коментар дълъг поне 10 символа, за да дадете репутация на този потребител.';
$l['add_toolong'] = 'Въведете причина не по-дълга от {1} символа.';
$l['add_negative_disabled'] = 'Администраторът е деактивирал отрицателната репутация.';
$l['add_neutral_disabled'] = 'Администраторът е деактивирал неутралната репутация.';
$l['add_positive_disabled'] = 'Администраторът е деактивирал положителната репутация.';
$l['add_all_rep_disabled'] = 'Администраторът е деактивирал всякакъв вид репутация. Не можете да оцените този потребител.';
$l['reputation_report'] = 'Отчет за репутация на {1}';
$l['reputation_members'] = 'Репутация от членове:';
$l['reputation_posts'] = 'Репутация от публикации:';
$l['summary'] = 'Обобщение';
$l['total_reputation'] = 'Общо репутация';
$l['post_reputation'] = 'Репутация от публикации';
$l['positive_count'] = 'Позитивни';
$l['neutral_count'] = 'Неутрални';
$l['negative_count'] = 'Негативни';
$l['last_week'] = 'Последната седмица';
$l['last_month'] = 'Последния месец';
$l['last_6months'] = 'Последните 6 месеца';
$l['comments'] = 'Коментари';
$l['close_window'] = 'Затвори прозорец';
$l['go_back'] = 'Назад';
$l['add_reputation_vote'] = 'Дай репутация на {1}';
$l['add_reputation_to_post'] = 'Тази репутация е за публикацията на {1}.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>Негативната репутация в момента е деактивирана</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em>Позитивната репутация в момента е деактивирана</em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em>Неутралната репутация в момента е деактивирана</em></span>';
$l['no_comment_needed'] = 'Давате репутация заради публикацията на този потребител, която е свързан с неговия профил. Коментар не е задължителен, но ако имате желание да оставите, моля, въведете го отдолу.<br />';
$l['no_comment'] = '[Без коментар]';
$l['vote_added'] = 'Рейтинг добавен';
$l['vote_updated'] = 'Рейтинг обновен';
$l['vote_deleted'] = 'Рейтинг итрит';
$l['vote_added_message'] = 'Вашата оценка беше успешно добавена за този потребител.';
$l['vote_updated_message'] = 'Вашата оценка беше успешно обновена за този потребител.';
$l['vote_deleted_message'] = 'Оценката беше успешно изтрита за този потребител.';
$l['update_reputation_vote'] = 'Обновете оценката за {1}';
$l['positive'] = 'Позитивна';
$l['negative'] = 'Отрицателна';
$l['neutral'] = 'Неутрална';
$l['user_comments'] = 'Вашите коментари за {1}:';
$l['add_vote'] = 'Добави рейтинг';
$l['update_vote'] = 'Обнови рейтинг';
$l['delete_vote'] = 'Изтрий рейтинг';
$l['power_positive'] = 'Положителна ({1})';
$l['power_neutral'] = 'Неутрална';
$l['power_negative'] = 'Отрицателна ({1})';
$l['show_all'] = 'Покажи: Всички гласове';
$l['show_positive'] = 'Покажи: Положителни оценки';
$l['show_neutral'] = 'Покажи: Неутрални оценки';
$l['show_negative'] = 'Покажи: Негативни оценки';
$l['sort_updated'] = 'Сорт. по: Последно обновени';
$l['sort_username'] = 'Сорт. по: Потребителско име';
$l['last_updated'] = 'Последно обновена {1}';
$l['postrep_post'] = 'Публикация #';
$l['postrep_given'] = 'Оценка дадена за <a href="{1}">публикация на {2}</a> {3}<br />';
$l['no_reputation_votes'] = 'В момента потребителя няма никаква репутация по посочения отдолу критерии.';
$l['delete_reputation_confirm'] = 'Сигурни ли сте, че искате да изтриете тази оценка?';
$l['delete_reputation_log'] = 'Изтрита оценка от {1} (UID: {2})';
$l['reputations_disabled_group'] = 'Системата за репутация е деактивирана за тази потребителска група.';
$l['rate_user'] = 'Оцени потребител';
$l['all_time'] = 'Всички времена';
$l['report_vote'] = 'Докладвай';
$l['postrep_given_thread'] = 'в <a href="{1}">{2}</a>';
$l['postrep_given_nolink'] = 'Дадена оценка за публикацията на {1}<br />';
