<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 21:47:26 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Търсене';
$l['nav_results'] = 'Резултати';
$l['pages_last'] = 'последен';
$l['search'] = 'Търси';
$l['search_keyword'] = 'Търси по ключова дума';
$l['search_username'] = 'Търси по име на потребител';
$l['search_entire_post'] = 'търси в цялата тема';
$l['search_titles_only'] = 'търси само в заглавията';
$l['match_username'] = 'точно съвпадение на име';
$l['search_forums'] = 'Търсене във форум(и)<br /><i><sub>* за повече от един избор задръжте Ctrl и маркирайте желаните форуми.</sub></i>';
$l['search_all_forums'] = 'Търси във всички отворени форуми';
$l['search_options'] = 'Опции за търсене';
$l['threads_at_least'] = 'Търси теми с поне';
$l['threads_at_most'] = 'Търси теми с поне';
$l['find_anydate'] = 'Търси публикации от всички дати';
$l['find_yesterday'] = 'Търси публикации от вчера';
$l['find_lastweek'] = 'Търси публикации от 1 седмица';
$l['find_2weeks'] = 'Търси публикации от 2 седмици';
$l['find_month'] = 'Търси публикации от 1 месец';
$l['find_3months'] = 'Търси публикации от 3 месеца';
$l['find_6months'] = 'Търси публикации от 6 месеца';
$l['find_year'] = 'Търси публикации от 1 година';
$l['and_newer'] = 'и по-нови';
$l['and_older'] = 'и по-стари';
$l['sorting_options'] = 'Опции за сортиране';
$l['sort_lastpost'] = 'По последна дата на публикация';
$l['sort_author'] = 'По автор';
$l['sort_forum'] = 'По форум';
$l['sort_in'] = 'във';
$l['sort_asc'] = 'възходящ';
$l['sort_desc'] = 'низходящ';
$l['sort_order'] = 'ред';
$l['asc'] = 'възх.';
$l['desc'] = 'низх.';
$l['display_options'] = 'Изглед';
$l['show_results_as'] = 'Покажи резултатите като';
$l['show_results_threads'] = 'теми';
$l['show_results_posts'] = 'публикации';
$l['search_results'] = 'Резултати от търсенето';
$l['post'] = 'Публикация';
$l['author'] = 'Автор';
$l['forum'] = 'Форум';
$l['replies'] = 'Отговори';
$l['views'] = 'Разглеждания';
$l['posted'] = 'Публикуван';
$l['thread'] = 'Тема';
$l['lastpost'] = 'Последна публикация';
$l['post_thread'] = 'Тема:';
$l['post_subject'] = 'Публикация:';
$l['replies2'] = 'отговора';
$l['selectall'] = 'Изберете всички допълнителни резултати?';
$l['any_prefix'] = 'Намери теми с всякакъв префикс';
$l['no_prefix'] = 'Без префикс';
$l['inline_thread_moderation'] = 'Бързо модериране на тема:';
$l['close_threads'] = 'Затвори теми';
$l['open_threads'] = 'Отвори теми';
$l['stick_threads'] = 'Закачи теми';
$l['unstick_threads'] = 'Откачи теми';
$l['delete_threads'] = 'Изтрий теми';
$l['move_threads'] = 'Премести теми';
$l['approve_threads'] = 'Одобри теми';
$l['unapprove_threads'] = 'Отхвърли теми';
$l['inline_delete_posts'] = 'Изтрий публикации';
$l['inline_merge_posts'] = 'Съедини публикации';
$l['inline_split_posts'] = 'Раздели публикации';
$l['inline_approve_posts'] = 'Одобри публикации';
$l['inline_unapprove_posts'] = 'Отхвърли публикации';
$l['inline_post_moderation'] = 'Бързо модериране на публикации:';
$l['inline_go'] = 'Отиди';
$l['clear'] = 'Изчисти';
$l['icon_dot'] = 'Съдържа ваши публикации. ';
$l['icon_new'] = 'Нови публикации.';
$l['icon_hot'] = 'Горещи теми.';
$l['icon_lock'] = 'Заключени теми.';
$l['attachment_count'] = 'Тази тема съдържа 1 прикачен файл.';
$l['attachment_count_multiple'] = 'Тази тема съдържа {1} прикачен файл.';
$l['goto_first_unread'] = 'Отиди на първата непрочетена публикация';
$l['page_selected'] = 'Всичките <strong>{1}</strong> резултата на тази страница са избрани.';
$l['all_selected'] = 'Всичките <strong>{1}</strong> резултата в това търсене са избрани.';
$l['select_all'] = 'Избери всичките <strong>{1}</strong> резултата в това търсене.';
$l['clear_selection'] = 'Изчисти избраните.';
$l['results'] = 'резултати';
$l['mod_options'] = 'Модераторски опции';
$l['find_all'] = 'Намери всички';
$l['find_only_approved'] = 'Намери само одобрените';
$l['find_only_unapproved'] = 'Намери само отхвърлените';
$l['redirect_searchresults'] = 'Благодарим, Вашето търсене беше изпълнено и ще бъдете пренасочени към списъка с резултатите.';
$l['error_minsearchlength'] = 'Един или няколко от условията за търсене са били по-кратки от минималната дължина. Минималната дължина е {1} символа.<br /><br />Ако се опитвате да търсите точна фраза я оградете в кавички. Например "Аз съм българче. Обичам наште планини зелени".';
$l['error_nosearchresults'] = 'Съжаляваме, но не бяха намерени резултати по зададената от Вас информация. Моля, променете условията за търсене и опитайте отново.';
$l['error_no_search_support'] = 'Базата данни не поддържа търсене.';
$l['error_nosearchterms'] = 'Не сте въвели никакви условия за търсене. Трябва да въведете някакво услове за търсене или потребителско име за търсене.';
$l['error_searchflooding_1'] = 'Съжаляваме, но можете да извършите само едно търсене на всеки {1} секунди. Моля, изчакайте 1 секунда преди да търсите отново.';
$l['error_searchflooding'] = 'Съжаляваме, но можете да извършите само едно търсене на всеки {1} секунди. Моля, изчакайте {2} секунди преди да търсите отново.';
$l['error_invalidsearch'] = 'Невалидно търсене. Моля, върнете се и опитайте отново.';
$l['inline_soft_delete_posts'] = 'Бързо изтриване на публикации';
$l['inline_restore_posts'] = 'Възстановяване на публикации';
$l['icon_no_new'] = 'Няма нови публикации.';
$l['search_user'] = 'Търси за потребител';
$l['display_all'] = 'Покажи всички';
$l['display_only_approved'] = 'Покажи само одобрените';
$l['display_only_unapproved'] = 'Покажи само неодобрените';
$l['display_only_softdeleted'] = 'Покажи само нежно изтритите';
$l['soft_delete_threads'] = 'Обратимо изтриване';
$l['restore_threads'] = 'Възстанови Теми';
$l['inline_move_posts'] = 'Премести публикации';
