<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Fri, 02 Jan 2015 23:33:30 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Изпрати тема на приятел';
$l['send_thread'] = 'Изпрати на приятел';
$l['recipient'] = 'Получател:';
$l['recipient_note'] = 'Въведи e-mail адрес на приятел.';
$l['subject'] = 'Заглавие:';
$l['message'] = 'Съобщение:';
$l['error_nosubject'] = 'Изисква се въвеждане на заглавие, за да изпратите темата на приятел';
$l['error_nomessage'] = 'Изисква се въвеждане на съобщение, за да изпратите темата на приятел';
$l['image_verification'] = 'Верификация на изображение';
$l['verification_subnote'] = '(чувствителен на символи)';
$l['verification_note'] = 'Моля, въведете текста съдържащ се в изображението в полето под него. Този процес се използва за предотвратяване на автоматизирани процеси.';
