<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra&GH0STFACE
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Mon, 05 Jan 2015 11:56:01 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Изтрий анкетата';
$l['close_thread'] = 'Заключи темата';
$l['stick_thread'] = 'Закачи темата';
$l['author'] = 'Автор';
$l['message'] = 'Съобщение';
$l['threaded'] = 'Нишков режим';
$l['linear'] = 'Линеен режим';
$l['next_oldest'] = 'Следващата по-стара';
$l['next_newest'] = 'Следващата по-нова';
$l['view_printable'] = 'Версия за принтиране';
$l['send_thread'] = 'Изпрати темата на приятел';
$l['subscribe_thread'] = 'Абониране за темата';
$l['unsubscribe_thread'] = 'Прекратяване на абонамента';
$l['moderation_options'] = 'Модераторски настройки:';
$l['delayed_moderation'] = 'Отложено модериране';
$l['thread_notes'] = 'Преглед/Редактиране на бележките';
$l['open_close_thread'] = 'Отключи/Заключи темата';
$l['approve_thread'] = 'Одобри темата';
$l['unapprove_thread'] = 'Отхвърли темата';
$l['delete_thread'] = 'Изтрий темата за винаги';
$l['delete_posts'] = 'Изтрий избраните публикации';
$l['move_thread'] = 'Премести/Копирай темата';
$l['stick_unstick_thread'] = 'Закачи/Откачи темата';
$l['split_thread'] = 'Отдели публикацията в нова тема';
$l['merge_threads'] = 'Обедини темите';
$l['merge_posts'] = 'Обедини избраните публикации';
$l['remove_redirects'] = 'Премахни препращанията';
$l['remove_subscriptions'] = 'Премахни всички абонаменти';
$l['poll'] = 'Анкета:';
$l['show_results'] = 'Резултатите';
$l['edit_poll'] = 'Редактиране на анкетата';
$l['public_note'] = '<b>Забележка:</b> Анкетата е публична и потребителите ще могат да виждат как сте гласували.';
$l['total'] = 'Общо';
$l['vote'] = 'Гласувайте!';
$l['total_votes'] = '{1} гласа';
$l['you_voted'] = '* Гласували сте за този елемент.';
$l['poll_closed'] = 'Анкетата е затворена.';
$l['already_voted'] = 'Вече сте гласували в анкетата.';
$l['undo_vote'] = 'Отказ от избора';
$l['quick_reply'] = 'Бърз отговор';
$l['message_note'] = 'Въведете вашия отговор в кутията отдясно';
$l['signature'] = 'Подписване';
$l['email_notify'] = 'Известяване с e-mail';
$l['disable_smilies'] = 'Деактивиране на емотиконите';
$l['post_reply'] = 'Нов отговор';
$l['post_reply_img'] = 'Нов отговор';
$l['post_thread'] = 'Нова тема';
$l['preview_post'] = 'Преглед';
$l['rating_average'] = '{1} гласа - средно {2}';
$l['rate_thread'] = 'Оценка на темата:';
$l['thread_rating'] = 'Оценете темата:';
$l['similar_threads'] = 'Теми, които вероятно са свързани...';
$l['thread'] = 'Тема:';
$l['replies'] = 'Отговори:';
$l['views'] = 'Прегледи:';
$l['lastpost'] = 'Последна публикация';
$l['messages_in_thread'] = 'Съобщения в темата';
$l['users_browsing_thread'] = 'Потребители разглеждащи темата:';
$l['users_browsing_thread_guests'] = '{1} гост(и)';
$l['users_browsing_thread_invis'] = '{1} потребител(и) в режим "инкогнито"';
$l['users_browsing_thread_reading'] = 'В момента четат...';
$l['inline_delete_posts'] = 'Изтрий публикациите';
$l['inline_merge_posts'] = 'Обедини публикациите';
$l['inline_split_posts'] = 'Отдели публикациите в нова тема';
$l['inline_approve_posts'] = 'Одобри публикациите';
$l['inline_unapprove_posts'] = 'Отхвърли публикациите';
$l['inline_post_moderation'] = 'Бърза модерация на публикацията:';
$l['inline_go'] = 'Приложи';
$l['clear'] = 'Изчисти';
$l['thread_closed'] = 'Темата е заключена';
$l['no_subject'] = 'Няма заглавие';
$l['error_nonextnewest'] = 'Няма по-нови теми от последната, която прегледахте.';
$l['error_nonextoldest'] = 'Няма по-стари теми от последната, която прегледахте.';
$l['quickreply_multiquote_selected'] = 'Избрали сте една или повече публикации за цитиране.';
$l['quickreply_multiquote_now'] = 'Цитиране в отговора';
$l['or'] = 'или';
$l['quickreply_multiquote_deselect'] = 'отхвърляне на избора';
$l['search_thread'] = 'Търси в темата';
$l['enter_keywords'] = 'Въведете ключови думи';
$l['image_verification'] = 'Одобрение на изображението';
$l['verification_note'] = 'Моля, въведете текста от изображението в ляво в текстовото поле по-долу. Този процес се използва, за да се предотвратят автоматизирани публикации.';
$l['verification_subnote'] = '(чувствително на символи)';
$l['thread_modes'] = 'Режими за темата';
$l['add_poll_to_thread'] = 'Добави анкета в тази тема';
$l['soft_delete_thread'] = 'Бързо изтриване на тема';
$l['restore_thread'] = 'Възстанови тема';
$l['poll_closes'] = 'Тази анкета ще затвори на: {1}';
$l['new_reply'] = 'Нов отговор';
$l['search_button'] = 'Търси';
$l['inline_soft_delete_posts'] = 'Бързо изтриване на публикациите';
$l['inline_restore_posts'] = 'Възстанови публикациите';
$l['inline_move_posts'] = 'Премести публикациите';
$l['view_thread_notes'] = 'Бележки за темата';
$l['view_all_notes'] = 'Виж всички бележки';
$l['save_changes'] = 'Запази промените';
$l['cancel_edit'] = 'Откажи редактиране';
$l['quick_edit_update_error'] = 'Имаше грешка при редактиране на отговор:';
$l['quick_reply_post_error'] = 'Имаше грешка при публикуване на отговор:';
$l['quick_delete_error'] = 'Имаше грешка при изтриване на отговор:';
$l['quick_delete_success'] = 'Публикацията беше изтрита успешно.';
$l['quick_delete_thread_success'] = 'Темата беше изтрита успешно.';
$l['quick_restore_error'] = 'Имаше грешка при възстановяване на отговор:';
$l['quick_restore_success'] = 'Публикацията беше възстановена успешно. ';
