<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 21:20:40 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Екип';
$l['forum_team'] = 'Екип';
$l['moderators'] = 'Модератори';
$l['mod_username'] = 'Потребителско име';
$l['mod_forums'] = 'Форум(и)';
$l['mod_email'] = 'E-mail';
$l['mod_pm'] = 'ЛС';
$l['uname'] = 'Потребителско име';
$l['email'] = 'E-mail';
$l['pm'] = 'ЛС';
$l['group_leaders'] = 'Лидер(и)';
$l['group_members'] = 'Член(ове)';
$l['no_members'] = 'Няма членове в тази група';
$l['error_noteamstoshow'] = 'Няма екип на форума за показване.';
$l['username'] = 'Потребителско име';
$l['lastvisit'] = 'Последно посещение';
$l['online'] = 'Онлайн';
$l['offline'] = 'Офлайн';
$l['away'] = 'Отсъстващ';
