<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra & AndroidBG.com
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : admin
// Last edited date : Tue, 23 May 2017 23:24:08 +0000
// --------------------------------------------------------------------------------

$l['socialsites'] = 'Социални мрежи';
$l['socialsites_user_on'] = '{1} в {2}';
$l['socialsites_icon'] = 'Иконка';
$l['socialsites_site'] = 'Име';
$l['socialsites_details'] = 'Линк към профила';
$l['socialsites_submit'] = 'Добави социални мрежи';
$l['socialsites_updated'] = 'Социалните мрежи са обновени успешно.';
$l['socialsites_expand'] = '(Покажи повече)';
$l['socialsites_collapse'] = '(Покажи по-малко)';
$l['socialsites_wol'] = 'Управление на <a href="usercp.php?action=socialsites">Ссоциални мрежи</a>';
