<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Fri, 02 Jan 2015 23:43:46 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Статистика на форума';
$l['board_stats'] = 'Статистика на форума';
$l['none'] = 'Няма';
$l['nobody'] = 'Никой';
$l['totals'] = 'Общо';
$l['averages'] = 'Средно';
$l['posts'] = 'Публикации:';
$l['threads'] = 'Теми:';
$l['members'] = 'Потребители:';
$l['ppd'] = 'Публикации на ден:';
$l['tpd'] = 'Теми на ден:';
$l['mpd'] = 'Потребители на ден:';
$l['ppm'] = 'Публикации/потребител:';
$l['rpt'] = 'Отговори на тема:';
$l['no_posts'] = 'Няма';
$l['general'] = 'Главни';
$l['newest_member'] = 'Най-нов потребител:';
$l['members_posted'] = 'Потребители, които са публикували:';
$l['todays_top_poster'] = 'Днешният топ публикуващ: <b>{1}</b> (<b>{2}</b> публикации)';
$l['popular_forum'] = 'Най-популярен форум: <b>{1}</b> (<b>{2}</b> публикации, <b>{3}</b> теми)';
$l['most_popular'] = 'Най-популярни...';
$l['most_replied_threads'] = 'Най-много отговори в теми';
$l['most_viewed_threads'] = 'Най-разглеждани теми';
$l['not_enough_info_stats'] = 'Съжаляваме, но няма достатъчно информация за този форум. За да се генерира статистика този форум трябва да има поне един потребител и поне една тема.';
$l['replies'] = 'отговора';
$l['views'] = 'разглеждания';
$l['stats_disabled'] = 'Не можете да видите статистиката, тъй като е деактивирана от Администратор.';
$l['tpm'] = 'Теми на член:';
$l['top_referrer'] = 'Топ референт:  <strong>{1}</strong> (<strong>{2}</strong> реферали)';
