<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Sat, 03 Jan 2015 00:21:17 +0000
// --------------------------------------------------------------------------------

$l['all_forums'] = 'Всички форуми:';
$l['forum'] = 'Форум:';
$l['posted_by'] = 'Започнато от:';
$l['on'] = 'Вкл.';
$l['portal'] = 'Портал';
