<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Fri, 02 Jan 2015 20:20:48 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '250';
$l['ucp_nav_menu'] = 'Меню';
$l['ucp_nav_messenger'] = 'Съобщения';
$l['ucp_nav_compose'] = 'Състави';
$l['ucp_nav_tracking'] = 'Проследяване';
$l['ucp_nav_edit_folders'] = 'Редактирай папки';
$l['ucp_nav_profile'] = 'Вашият профил';
$l['ucp_nav_edit_profile'] = 'Редактирай профил';
$l['ucp_nav_edit_options'] = 'Настройки на форума';
$l['ucp_nav_change_email'] = 'Промени е-mail';
$l['ucp_nav_change_pass'] = 'Промени парола';
$l['ucp_nav_change_username'] = 'Промени потребителско име';
$l['ucp_nav_edit_sig'] = 'Промени подпис';
$l['ucp_nav_change_avatar'] = 'Промени аватар';
$l['ucp_nav_misc'] = 'Разни';
$l['ucp_nav_editlists'] = 'Списък с Приятели/Игнорирани';
$l['ucp_nav_favorite_threads'] = 'Любими теми';
$l['ucp_nav_subscribed_threads'] = 'Абонирани теми';
$l['ucp_nav_forum_subscriptions'] = 'Форумни абонаменти';
$l['ucp_nav_drafts'] = 'Чернови';
$l['ucp_nav_notepad'] = 'Личен бележник';
$l['ucp_nav_view_profile'] = 'Виж профил';
$l['ucp_nav_home'] = 'Начало';
$l['ucp_nav_usergroups'] = 'Членство в групи';
$l['ucp_nav_attachments'] = 'Мениджър на файлове';
$l['ucp_nav_drafts_active'] = '<strong>Запаметени чернови ({1})</strong>';
