<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Bulgarian (български)
// Author of the language pack : NEOhidra
// Language pack translators website : http://community.mybb.com/user-23021.html
// Compatible version of MyBB : 1607
// Last edited in MyBB Editor by : GH0STFACE
// Last edited date : Fri, 02 Jan 2015 23:49:35 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = 'Не сте въвели ново заглавие.';
$l['post_moderation'] = 'Вашата публикация в момента се модерира.';
$l['post_doesnt_exist'] = 'Посочената публикация не съществува.';
$l['thread_doesnt_exist'] = 'Посочената тема не съществува.';
$l['thread_closed_edit_subjects'] = 'Тази тема е затворена и не можете да редактирате заглавието.';
$l['no_permission_edit_subject'] = 'Нямате права за редакция на заглавието на тази тема.';
$l['thread_closed_edit_message'] = 'Тази тема е затворена и не можете да редактирате публикации в нея.';
$l['no_permission_edit_post'] = 'Нямате права за редакция на тази публикация.';
$l['edit_time_limit'] = 'Можете да редактирате публикации само в рамките на {1} минути от тяхното публикуване.';
$l['postbit_edited'] = 'Тази публикация е последно редактирана: {1} от';
$l['save_changes'] = 'Запамети промените';
$l['cancel_edit'] = 'Откажи редакцията';
$l['captcha_not_exists'] = 'Изображението за верификация, което се опитвате да опресните не съществува.';
$l['captcha_valid_not_exists'] = 'Изображението за верификация, което се опитвате да проверите не съществува.';
$l['captcha_does_not_match'] = 'Кодът за потвърждение, който въвеждате е неправилен. Моля, въведете кода точно, както се вижда на изображението.';
$l['captcha_matches'] = 'Въведеният верификационен код беше правилен.';
$l['banned_username'] = 'Въведеното потребителско име е забранено от администратора';
$l['banned_characters_username'] = 'Вашето потребителско име съдържа един или няколко невалидни символа';
$l['complex_password_fails'] = 'Паролата изисква главна буква, малка биква и цифра';
$l['username_taken'] = '{1} вече е регистриран от друг член';
$l['username_available'] = '{1} е на разположение';
$l['invalid_username'] = '{1} не е потребителско име на регистриран член';
$l['valid_username'] = '{1} е валиден референт.';
$l['buddylist_error'] = 'Изглежда нямате приятели във Вашия списък с приятели. Моля, добавете някого преди да го използвате.';
$l['close'] = 'Затвори';
$l['select_buddies'] = 'Избери приятели';
$l['select_buddies_desc'] = 'За да добавите един или няколко приятели като получатели ги изберете и натиснете OK.';
$l['selected_recipients'] = 'Избрани получатели';
$l['ok'] = 'ОК';
$l['cancel'] = 'Откажи';
$l['online'] = 'Онлайн';
$l['offline'] = 'Офлайн';
$l['edited_post'] = 'Редактирана публикация';
$l['usergroup'] = 'Потребителска група';
$l['thread_moderation'] = 'Вашата тема в момента се модерира.';
$l['postbit_editreason'] = 'Редактирай причина';
$l['answer_valid_not_exists'] = 'Върпосът на който се опитвате да отговорите не съществува.';
$l['answer_does_not_match'] = 'Отговорът, който въведохте е неправилен.';
